In [1]:
import pandas as pd
import numpy as np
from datetime import date
from datetime import datetime

In [2]:
Data=pd.read_csv("C://Users//shawnhe//Downloads//payments_2021-09-01_2021-09-22.csv")

AP=pd.read_csv("C://Users//shawnhe//Downloads//2021Sep1-2021Sep22CustomTransaction.csv")

Data = Data[Data["transaction_kind"]!="void"]

Data_AP=Data[Data["payment_method"]=="Amazon payments"]

Data_AP=Data_AP[["day","customer_name","order_name","customer_email","total_payments"]]

In [3]:
AP

,TransactionPostedDate,SettlementId,AmazonTransactionId,SellerReferenceId,TransactionType,AmazonOrderReferenceId,SellerOrderId,StoreName,CurrencyCode,TransactionDescription,TransactionAmount,TransactionPercentageFee,TransactionFixedFee,TotalTransactionFee,NetTransactionAmount,Unnamed: 15
0,2021-09-01T06:46:35 -0700,14776129271,NaN,NaN,Transfer,NaN,NaN,NaN,USD,Disbursement_AccountEndingWithAndWithTraceId,-615.53,0.00,0.0,0.00,-615.53,NaN
1,2021-09-01T10:55:08 -0700,14776129271,P01-3664545-7719067-R049151,a778f4d6259846a293764889a155f4d5,Refund,P01-3664545-7719067,Checkout #21296232824926,Ming Wang,USD,NaN,-86.99,2.39,0.0,2.39,-84.60,NaN
2,2021-09-01T10:59:37 -0700,14776129271,P01-8424090-2091544-R076014,09773f8479d0b704abdbe4ba19dec243,Refund,P01-8424090-2091544,Checkout #21296187113566,Ming Wang,USD,NaN,-130.00,3.58,0.0,3.58,-126.42,NaN
3,2021-09-01T12:39:32 -0700,14776129271,P01-9077609-7879042-C074237,d4b50970450f69834e4905a809ba5a1a,Capture,P01-9077609-7879042,Checkout #21573969510494,Ming Wang,USD,NaN,210.00,-5.78,-0.3,-6.08,203.92,NaN
4,2021-09-02T09:33:40 -0700,14780823111,P01-3694982-3104358-C078747,f37274374ed0b83bc5d0af3a45e29c84,Capture,P01-3694982-3104358,Checkout #21582092009566,Ming Wang,USD,NaN,50.87,-1.40,-0.3,-1.70,49.17,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,2021-09-22T06:44:41 -0700,14872350421,NaN,NaN,Transfer,NaN,NaN,NaN,USD,Disbursement_AccountEndingWithAndWithTraceId,"-2,408.35",0.00,0.0,0.00,"-2,408.35",NaN
77,2021-09-22T08:30:52 -0700,14872350421,P01-9419432-1713955-C060905,cecc8f072b743d6605ff838d61b0016a,Capture,P01-9419432-1713955,Checkout #21792033570910,Ming Wang,USD,NaN,74.40,-2.05,-0.3,-2.35,72.05,NaN
78,2021-09-22T10:32:50 -0700,14872350421,P01-9783805-4780810-C044594,4dab7f8574c499813ea69cf1cfd9efb9,Capture,P01-9783805-4780810,Checkout #21795206004830,Ming Wang,USD,NaN,74.40,-2.05,-0.3,-2.35,72.05,NaN
79,2021-09-22T10:33:47 -0700,14872350421,P01-8082012-7293725-C056601,db5e877ba6aa18100da850fc7e3aebe4,Capture,P01-8082012-7293725,Checkout #21799200456798,Ming Wang,USD,NaN,172.50,-4.74,-0.3,-5.04,167.46,NaN
80,2021-09-22T10:33:55 -0700,14872350421,P01-2155889-6239601-C079628,076f01b64cfa3f363a5aba2709dc125e,Capture,P01-2155889-6239601,Checkout #21798457475166,Ming Wang,USD,NaN,181.98,-5.00,-0.3,-5.30,176.68,NaN

In [4]:
Data_AP["day"]

26      2021-09-21
28      2021-09-21
36      2021-09-21
51      2021-09-05
70      2021-09-10
           ...
1362    2021-09-15
1367    2021-09-13
1371    2021-09-09
1387    2021-09-21
1388    2021-09-07
Name: day, Length: 67, dtype: object

In [5]:
date_format = "%Y-%m-%d"
Data_AP["day"]=Data_AP["day"].apply(lambda x : datetime.strptime(x, date_format))

In [6]:
Data_AP["Lookup_1"]=(Data_AP["day"].apply(lambda x: (x-datetime.strptime("1900-01-01", date_format)).days+2)).astype(str)+"|"+Data_AP["total_payments"].astype(str)

In [7]:
Data_AP["Lookup_1"]

26        44460|920.0
28        44460|904.0
36        44460|810.0
51        44444|694.4
70        44449|624.0
            ...
1362     44454|-220.0
1367    44452|-227.33
1371    44448|-232.74
1387     44460|-295.0
1388     44446|-295.0
Name: Lookup_1, Length: 67, dtype: object

In [8]:
Data_AP["Lookup_1"]=Data_AP["Lookup_1"].mask(Data_AP["Lookup_1"].str[-1]=="0",Data_AP["Lookup_1"].str[:-1])
Data_AP["Lookup_1"]=Data_AP["Lookup_1"].mask(Data_AP["Lookup_1"].str[-1]==".",Data_AP["Lookup_1"].str[:-1])
Data_AP["Lookup_1"]=Data_AP["Lookup_1"].apply(lambda x:x.replace(',',''))
Data_AP["Lookup_1"]

26          44460|920
28          44460|904
36          44460|810
51        44444|694.4
70          44449|624
            ...
1362       44454|-220
1367    44452|-227.33
1371    44448|-232.74
1387       44460|-295
1388       44446|-295
Name: Lookup_1, Length: 67, dtype: object

In [26]:
Data_AP=Data_AP[["day","Lookup_1","customer_name","customer_email","order_name","total_payments"]]
Data_AP.sort_values("day",ascending=True,inplace=True)
Data_AP.to_csv("C://Users//shawnhe//Desktop//AP_Left.csv",index=False)

In [10]:
AP

,TransactionPostedDate,SettlementId,AmazonTransactionId,SellerReferenceId,TransactionType,AmazonOrderReferenceId,SellerOrderId,StoreName,CurrencyCode,TransactionDescription,TransactionAmount,TransactionPercentageFee,TransactionFixedFee,TotalTransactionFee,NetTransactionAmount,Unnamed: 15
0,2021-09-01T06:46:35 -0700,14776129271,NaN,NaN,Transfer,NaN,NaN,NaN,USD,Disbursement_AccountEndingWithAndWithTraceId,-615.53,0.00,0.0,0.00,-615.53,NaN
1,2021-09-01T10:55:08 -0700,14776129271,P01-3664545-7719067-R049151,a778f4d6259846a293764889a155f4d5,Refund,P01-3664545-7719067,Checkout #21296232824926,Ming Wang,USD,NaN,-86.99,2.39,0.0,2.39,-84.60,NaN
2,2021-09-01T10:59:37 -0700,14776129271,P01-8424090-2091544-R076014,09773f8479d0b704abdbe4ba19dec243,Refund,P01-8424090-2091544,Checkout #21296187113566,Ming Wang,USD,NaN,-130.00,3.58,0.0,3.58,-126.42,NaN
3,2021-09-01T12:39:32 -0700,14776129271,P01-9077609-7879042-C074237,d4b50970450f69834e4905a809ba5a1a,Capture,P01-9077609-7879042,Checkout #21573969510494,Ming Wang,USD,NaN,210.00,-5.78,-0.3,-6.08,203.92,NaN
4,2021-09-02T09:33:40 -0700,14780823111,P01-3694982-3104358-C078747,f37274374ed0b83bc5d0af3a45e29c84,Capture,P01-3694982-3104358,Checkout #21582092009566,Ming Wang,USD,NaN,50.87,-1.40,-0.3,-1.70,49.17,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,2021-09-22T06:44:41 -0700,14872350421,NaN,NaN,Transfer,NaN,NaN,NaN,USD,Disbursement_AccountEndingWithAndWithTraceId,"-2,408.35",0.00,0.0,0.00,"-2,408.35",NaN
77,2021-09-22T08:30:52 -0700,14872350421,P01-9419432-1713955-C060905,cecc8f072b743d6605ff838d61b0016a,Capture,P01-9419432-1713955,Checkout #21792033570910,Ming Wang,USD,NaN,74.40,-2.05,-0.3,-2.35,72.05,NaN
78,2021-09-22T10:32:50 -0700,14872350421,P01-9783805-4780810-C044594,4dab7f8574c499813ea69cf1cfd9efb9,Capture,P01-9783805-4780810,Checkout #21795206004830,Ming Wang,USD,NaN,74.40,-2.05,-0.3,-2.35,72.05,NaN
79,2021-09-22T10:33:47 -0700,14872350421,P01-8082012-7293725-C056601,db5e877ba6aa18100da850fc7e3aebe4,Capture,P01-8082012-7293725,Checkout #21799200456798,Ming Wang,USD,NaN,172.50,-4.74,-0.3,-5.04,167.46,NaN
80,2021-09-22T10:33:55 -0700,14872350421,P01-2155889-6239601-C079628,076f01b64cfa3f363a5aba2709dc125e,Capture,P01-2155889-6239601,Checkout #21798457475166,Ming Wang,USD,NaN,181.98,-5.00,-0.3,-5.30,176.68,NaN

In [11]:
AP=AP[["TransactionPostedDate","SettlementId","TransactionType","TransactionAmount","NetTransactionAmount"]]

In [12]:
AP["TransactionPostedDate"]=AP["TransactionPostedDate"].apply(lambda x : x[:10])

<ipython-input-12-a49fa7d5f29c>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  AP["TransactionPostedDate"]=AP["TransactionPostedDate"].apply(lambda x : x[:10])

In [13]:
AP["TransactionPostedDate"]

0     2021-09-01
1     2021-09-01
2     2021-09-01
3     2021-09-01
4     2021-09-02
         ...
76    2021-09-22
77    2021-09-22
78    2021-09-22
79    2021-09-22
80    2021-09-22
Name: TransactionPostedDate, Length: 81, dtype: object

In [14]:
AP_1=AP[AP["TransactionType"]!="Transfer"]
AP_1=AP_1[AP_1["TransactionType"]!="Debt"]

In [15]:
AP_2 = AP[AP["TransactionType"]!="Capture"]
AP_2 = AP_2[AP_2["TransactionType"]!="Refund"]
AP_2 = AP_2[AP_2["TransactionType"]!="Authorization"]

In [16]:
AP_CAPTURE=AP_1[["SettlementId","NetTransactionAmount"]]

In [17]:
AP_CAPTURE["NetTransactionAmount"]=AP_CAPTURE["NetTransactionAmount"].apply(lambda x : x.replace(",",""))
AP_CAPTURE["NetTransactionAmount"]=AP_CAPTURE["NetTransactionAmount"].apply(lambda x : float(x))

<ipython-input-17-f3d01a9e2457>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  AP_CAPTURE["NetTransactionAmount"]=AP_CAPTURE["NetTransactionAmount"].apply(lambda x : x.replace(",",""))
<ipython-input-17-f3d01a9e2457>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  AP_CAPTURE["NetTransactionAmount"]=AP_CAPTURE["NetTransactionAmount"].apply(lambda x : float(x))

In [18]:
AP_CAPTURE=AP_CAPTURE.groupby("SettlementId").sum()

In [19]:
AP_CAPTURE

              NetTransactionAmount
SettlementId
14776129271                  -7.10
14780823111                  49.17
14785987441                 377.67
14790834361                1629.99
14794806911                 393.05
14801454651                 320.21
14811287171                 176.65
14816858481                1135.28
14823037181                 380.42
14827705471                 953.29
14840845391                1218.08
14846259211                 282.29
14851715411                1695.88
14856765451                2408.35
14872350421                 488.24

In [20]:
AP_2["NetTransactionAmount"]=AP_2["NetTransactionAmount"].apply(lambda x : x.replace(",",""))
AP_2["TransactionAmount"]=AP_2["TransactionAmount"].apply(lambda x : x.replace(",",""))
AP_2

,TransactionPostedDate,SettlementId,TransactionType,TransactionAmount,NetTransactionAmount
0,2021-09-01,14776129271,Transfer,-615.53,-615.53
5,2021-09-03,14785987441,Transfer,-42.07,-42.07
15,2021-09-06,14794806911,Transfer,-377.67,-377.67
16,2021-09-06,14794806911,Transfer,-1629.99,-1629.99
25,2021-09-08,14801454651,Transfer,-393.05,-393.05
28,2021-09-09,14811287171,Transfer,-320.21,-320.21
32,2021-09-10,14816858481,Transfer,-176.65,-176.65
35,2021-09-13,14823037181,Transfer,-1135.28,-1135.28
40,2021-09-14,14827705471,Transfer,-380.42,-380.42
46,2021-09-15,14840845391,Transfer,-953.29,-953.29
56,2021-09-16,14846259211,Transfer,-1218.08,-1218.08
60,2021-09-17,14851715411,Transfer,-282.29,-282.29
68,2021-09-21,14856765451,Transfer,-1695.88,-1695.88
76,2021-09-22,14872350421,Transfer,-2408.35,-2408.35

In [21]:
AP_2["SettlementId"]=np.where(AP_CAPTURE["NetTransactionAmount"].astype("float64")==AP_2["NetTransactionAmount"].astype("float64")*(-1),AP_CAPTURE["SettlementId"])

ValueError: Can only compare identically-labeled Series objects

In [ ]:
AP_2=AP_2[["SettlementId","TransactionType","TransactionPostedDate","NetTransactionAmount"]]