In [1]:
import pandas as pd
import numpy as np
from datetime import date
from datetime import datetime
import numpy as np

In [2]:
kl=pd.read_csv("C://Users//shawnhe//Downloads//klarna-transactions-reports_2021-11-01T00-00-00Z_2021-11-30T23-59-59Z.csv")

In [3]:
kl=kl.apply(lambda x : x.str.replace('"',''))

In [4]:
kl.head()

  type;detailed_type;sale_date;capture_date;order_id;short_order_id;capture_id;merchant_reference1;merchant_reference2;merchant_capture_reference;merchant_refund_reference;amount;posting_currency;refund_id;purchase_country;shipping_address_country;tax_rate;tax_amount;initial_payment_method_type;initial_payment_method_number_of_installments;initial_payment_method_monthly_downpayments;merchant_id;settlement_currency;payment_reference;payout_date;klarna_comment;consumer_tax_rate_1;consumer_tax_amount_1;consumer_tax_rate_2;consumer_tax_amount_2;consumer_tax_rate_3;consumer_tax_amount_3;consumer_tax_rate_4;consumer_tax_amount_4
0  SALE;PURCHASE;2021-11-26T23:27:22.643Z;2021-11...
1  FEE;PURCHASE_FEE_FIXED;2021-11-26T23:27:22.643...
2  FEE;PURCHASE_FEE_PERCENTAGE;2021-11-26T23:27:2...
3  FEE;PURCHASE_FEE_PERCENTAGE;2021-11-26T20:38:1...
4  SALE;PURCHASE;2021-11-26T20:38:16.402Z;2021-11...

In [5]:
kl["type;detailed_type;sale_date;capture_date;order_id;short_order_id;capture_id;merchant_reference1;merchant_reference2;merchant_capture_reference;merchant_refund_reference;amount;posting_currency;refund_id;purchase_country;shipping_address_country;tax_rate;tax_amount;initial_payment_method_type;initial_payment_method_number_of_installments;initial_payment_method_monthly_downpayments;merchant_id;settlement_currency;payment_reference;payout_date;klarna_comment;consumer_tax_rate_1;consumer_tax_amount_1;consumer_tax_rate_2;consumer_tax_amount_2;consumer_tax_rate_3;consumer_tax_amount_3;consumer_tax_rate_4;consumer_tax_amount_4"]

0     SALE;PURCHASE;2021-11-26T23:27:22.643Z;2021-11...
1     FEE;PURCHASE_FEE_FIXED;2021-11-26T23:27:22.643...
2     FEE;PURCHASE_FEE_PERCENTAGE;2021-11-26T23:27:2...
3     FEE;PURCHASE_FEE_PERCENTAGE;2021-11-26T20:38:1...
4     SALE;PURCHASE;2021-11-26T20:38:16.402Z;2021-11...
5     FEE;PURCHASE_FEE_FIXED;2021-11-26T20:38:16.402...
6     SALE;PURCHASE;2021-11-22T17:34:24.024Z;2021-11...
7     FEE;PURCHASE_FEE_PERCENTAGE;2021-11-22T17:34:2...
8     FEE;PURCHASE_FEE_FIXED;2021-11-22T17:34:24.024...
9     FEE;PURCHASE_FEE_PERCENTAGE;2021-11-21T04:19:4...
10    FEE;PURCHASE_FEE_FIXED;2021-11-21T04:19:49.720...
11    SALE;PURCHASE;2021-11-21T04:19:49.720Z;2021-11...
12    FEE;PURCHASE_FEE_FIXED;2021-11-18T20:38:58.057...
13    SALE;PURCHASE;2021-11-18T20:38:58.057Z;2021-11...
14    FEE;PURCHASE_FEE_PERCENTAGE;2021-11-18T20:38:5...
15    FEE;PURCHASE_FEE_PERCENTAGE;2021-11-13T15:03:3...
16    FEE;PURCHASE_FEE_FIXED;2021-11-13T15:03:32.746...
17    SALE;PURCHASE;2021-11-13T15:03:32.746Z;2021-11...
18    FEE;PURCHASE_FEE_FIXED;2021-11-12T06:06:26.373...
19    SALE;PURCHASE;2021-11-12T06:06:26.373Z;2021-11...
20    FEE;PURCHASE_FEE_PERCENTAGE;2021-11-12T06:06:2...
21    SALE;PURCHASE;2021-11-04T19:49:07.060Z;2021-11...
22    FEE;PURCHASE_FEE_PERCENTAGE;2021-11-04T19:49:0...
23    FEE;PURCHASE_FEE_FIXED;2021-11-04T19:49:07.060...
24    FEE;PURCHASE_FEE_PERCENTAGE;2021-11-03T14:32:2...
25    SALE;PURCHASE;2021-11-03T14:32:21.099Z;2021-11...
26    FEE;PURCHASE_FEE_FIXED;2021-11-03T14:32:21.099...
27    SALE;PURCHASE;2021-10-31T19:08:03.900Z;2021-11...
28    FEE;PURCHASE_FEE_FIXED;2021-10-31T19:08:03.900...
29    FEE;PURCHASE_FEE_PERCENTAGE;2021-10-31T19:08:0...
30    FEE;PURCHASE_FEE_FIXED;2021-10-30T12:59:34.154...
31    FEE;PURCHASE_FEE_PERCENTAGE;2021-10-30T12:59:3...
32    SALE;PURCHASE;2021-10-30T12:59:34.154Z;2021-11...
33    SALE;PURCHASE;2021-10-29T22:07:11.323Z;2021-11...
34    FEE;PURCHASE_FEE_PERCENTAGE;2021-10-29T22:07:1...
35    FEE;PURCHASE_FEE_FIXED;2021-10-29T22:07:11.323...
Name: type;detailed_type;sale_date;capture_date;order_id;short_order_id;capture_id;merchant_reference1;merchant_reference2;merchant_capture_reference;merchant_refund_reference;amount;posting_currency;refund_id;purchase_country;shipping_address_country;tax_rate;tax_amount;initial_payment_method_type;initial_payment_method_number_of_installments;initial_payment_method_monthly_downpayments;merchant_id;settlement_currency;payment_reference;payout_date;klarna_comment;consumer_tax_rate_1;consumer_tax_amount_1;consumer_tax_rate_2;consumer_tax_amount_2;consumer_tax_rate_3;consumer_tax_amount_3;consumer_tax_rate_4;consumer_tax_amount_4, dtype: object

In [6]:
kl[['type', 'detailed_type', 'sale_date', 'capture_date', 'order_id', 'short_order_id', 'capture_id', 'merchant_reference1', 'merchant_reference2', 'merchant_capture_reference', 'merchant_refund_reference', 'amount', 'posting_currency', 'refund_id', 'purchase_country', 'shipping_address_country', 'tax_rate', 'tax_amount', 'initial_payment_method_type', 'initial_payment_method_number_of_installments', 'initial_payment_method_monthly_downpayments', 'merchant_id', 'settlement_currency', 'payment_reference', 'payout_date', 'klarna_comment', 'consumer_tax_rate_1', 'consumer_tax_amount_1', 'consumer_tax_rate_2', 'consumer_tax_amount_2', 'consumer_tax_rate_3', 'consumer_tax_amount_3', 'consumer_tax_rate_4', 'consumer_tax_amount_4']]=kl[['type', 'detailed_type', 'sale_date', 'capture_date', 'order_id', 'short_order_id', 'capture_id', 'merchant_reference1', 'merchant_reference2', 'merchant_capture_reference', 'merchant_refund_reference', 'amount', 'posting_currency', 'refund_id', 'purchase_country', 'shipping_address_country', 'tax_rate', 'tax_amount', 'initial_payment_method_type', 'initial_payment_method_number_of_installments', 'initial_payment_method_monthly_downpayments', 'merchant_id', 'settlement_currency', 'payment_reference', 'payout_date', 'klarna_comment', 'consumer_tax_rate_1', 'consumer_tax_amount_1', 'consumer_tax_rate_2', 'consumer_tax_amount_2', 'consumer_tax_rate_3', 'consumer_tax_amount_3', 'consumer_tax_rate_4', 'consumer_tax_amount_4']]=kl["type;detailed_type;sale_date;capture_date;order_id;short_order_id;capture_id;merchant_reference1;merchant_reference2;merchant_capture_reference;merchant_refund_reference;amount;posting_currency;refund_id;purchase_country;shipping_address_country;tax_rate;tax_amount;initial_payment_method_type;initial_payment_method_number_of_installments;initial_payment_method_monthly_downpayments;merchant_id;settlement_currency;payment_reference;payout_date;klarna_comment;consumer_tax_rate_1;consumer_tax_amount_1;consumer_tax_rate_2;consumer_tax_amount_2;consumer_tax_rate_3;consumer_tax_amount_3;consumer_tax_rate_4;consumer_tax_amount_4"].str.split(';',expand=True)

In [7]:
kl=kl.iloc[:,1:]

In [8]:
kl

,type,detailed_type,sale_date,capture_date,order_id,short_order_id,capture_id,merchant_reference1,merchant_reference2,merchant_capture_reference,...,payout_date,klarna_comment,consumer_tax_rate_1,consumer_tax_amount_1,consumer_tax_rate_2,consumer_tax_amount_2,consumer_tax_rate_3,consumer_tax_amount_3,consumer_tax_rate_4,consumer_tax_amount_4
0,SALE,PURCHASE,2021-11-26T23:27:22.643Z,2021-11-28T14:16:37.000Z,abbd4306-72ce-5445-b04b-0beb9879b9e4,MBXT9P2P-1,b4dd929e-a7fd-4b0a-bed3-77e1d333a55e,P4204,4289572208806,,...,2021-12-02T00:00:00.000Z,,,,,,,,,
1,FEE,PURCHASE_FEE_FIXED,2021-11-26T23:27:22.643Z,2021-11-28T14:16:37.000Z,abbd4306-72ce-5445-b04b-0beb9879b9e4,MBXT9P2P-1,b4dd929e-a7fd-4b0a-bed3-77e1d333a55e,P4204,4289572208806,,...,2021-12-02T00:00:00.000Z,,,,,,,,,
2,FEE,PURCHASE_FEE_PERCENTAGE,2021-11-26T23:27:22.643Z,2021-11-28T14:16:37.000Z,abbd4306-72ce-5445-b04b-0beb9879b9e4,MBXT9P2P-1,b4dd929e-a7fd-4b0a-bed3-77e1d333a55e,P4204,4289572208806,,...,2021-12-02T00:00:00.000Z,,,,,,,,,
3,FEE,PURCHASE_FEE_PERCENTAGE,2021-11-26T20:38:16.402Z,2021-11-28T14:16:31.000Z,6db6e9b8-e891-6d35-8111-829134d3f4fb,0T9JD1VW-1,163a4ee0-185a-4b06-8d07-411325f8ef3b,P4195,4289036681382,,...,2021-12-02T00:00:00.000Z,,,,,,,,,
4,SALE,PURCHASE,2021-11-26T20:38:16.402Z,2021-11-28T14:16:31.000Z,6db6e9b8-e891-6d35-8111-829134d3f4fb,0T9JD1VW-1,163a4ee0-185a-4b06-8d07-411325f8ef3b,P4195,4289036681382,,...,2021-12-02T00:00:00.000Z,,,,,,,,,
5,FEE,PURCHASE_FEE_FIXED,2021-11-26T20:38:16.402Z,2021-11-28T14:16:31.000Z,6db6e9b8-e891-6d35-8111-829134d3f4fb,0T9JD1VW-1,163a4ee0-185a-4b06-8d07-411325f8ef3b,P4195,4289036681382,,...,2021-12-02T00:00:00.000Z,,,,,,,,,
6,SALE,PURCHASE,2021-11-22T17:34:24.024Z,2021-11-23T22:46:45.000Z,66bd063b-a4ec-5e5b-b2aa-e4678536ac12,5LK3B051-1,11d57c58-7c0d-40e2-bac4-03cd4a645dfc,P4098,4277877571750,,...,2021-11-27T00:00:00.000Z,,,,,,,,,
7,FEE,PURCHASE_FEE_PERCENTAGE,2021-11-22T17:34:24.024Z,2021-11-23T22:46:45.000Z,66bd063b-a4ec-5e5b-b2aa-e4678536ac12,5LK3B051-1,11d57c58-7c0d-40e2-bac4-03cd4a645dfc,P4098,4277877571750,,...,2021-11-27T00:00:00.000Z,,,,,,,,,
8,FEE,PURCHASE_FEE_FIXED,2021-11-22T17:34:24.024Z,2021-11-23T22:46:45.000Z,66bd063b-a4ec-5e5b-b2aa-e4678536ac12,5LK3B051-1,11d57c58-7c0d-40e2-bac4-03cd4a645dfc,P4098,4277877571750,,...,2021-11-27T00:00:00.000Z,,,,,,,,,
9,FEE,PURCHASE_FEE_PERCENTAGE,2021-11-21T04:19:49.720Z,2021-11-23T14:17:51.000Z,c0ba0b36-dfa7-5cc6-aa2e-d11502a0ddeb,9V8BPQSK-1,bf5f82e9-96bf-4f27-9999-0e096edb0ce1,P4075,4275734970534,,...,2021-11-27T00:00:00.000Z,,,,,,,,,
10,FEE,PURCHASE_FEE_FIXED,2021-11-21T04:19:49.720Z,2021-11-23T14:17:51.000Z,c0ba0b36-dfa7-5cc6-aa2e-d11502a0ddeb,9V8BPQSK-1,bf5f82e9-96bf-4f27-9999-0e096edb0ce1,P4075,4275734970534,,...,2021-11-27T00:00:00.000Z,,,,,,,,,
11,SALE,PURCHASE,2021-11-21T04:19:49.720Z,2021-11-23T14:17:51.000Z,c0ba0b36-dfa7-5cc6-aa2e-d11502a0ddeb,9V8BPQSK-1,bf5f82e9-96bf-4f27-9999-0e096edb0ce1,P4075,4275734970534,,...,2021-11-27T00:00:00.000Z,,,,,,,,,
12,FEE,PURCHASE_FEE_FIXED,2021-11-18T20:38:58.057Z,2021-11-19T16:19:03.000Z,8bbbf838-3b2d-626b-afab-7e793b88e4a3,860LL3L7-1,e50d18d2-f5e4-440f-a6b8-a24f94980f9b,P4041,4272258416806,,...,2021-11-23T00:00:00.000Z,,,,,,,,,
13,SALE,PURCHASE,2021-11-18T20:38:58.057Z,2021-11-19T16:19:03.000Z,8bbbf838-3b2d-626b-afab-7e793b88e4a3,860LL3L7-1,e50d18d2-f5e4-440f-a6b8-a24f94980f9b,P4041,4272258416806,,...,2021-11-23T00:00:00.000Z,,,,,,,,,
14,FEE,PURCHASE_FEE_PERCENTAGE,2021-11-18T20:38:58.057Z,2021-11-19T16:19:03.000Z,8bbbf838-3b2d-626b-afab-7e793b88e4a3,860LL3L7-1,e50d18d2-f5e4-440f-a6b8-a24f94980f9b,P4041,4272258416806,,...,2021-11-23T00:00:00.000Z,,,,,,,,,
15,FEE,PURCHASE_FEE_PERCENTAGE,2021-11-13T15:03:32.746Z,2021-11-16T16:18:04.000Z,87be42e4-1925-5c67-a0b0-e174a7fa2566,MV7FX6WG-1,9e177226-ca90-4db1-8339-2965d12c1576,P3954,4265319825574,,...,2021-11-20T00:00:00.000Z,,,,,,,,,
16,FEE,PURCHASE_FEE_FIXED,2021-11-13T15:03:32.746Z,2021-11-16T16:18:04.000Z,87be42e4-1925-5c67-a0b0-e174a7fa2566,MV7FX6WG-1,9e177226-ca90-4db1-8339-2965d12c1576,P3954,4265319825574,,...,2021-11-20T00:00:00.000Z,,,,,,,,,
17,SALE,PURCHASE,2021-11-13T15:03:32.746Z,2021-11-16T16:18:04.000Z,87be42e4-1925-5c67-a0b0-e174a7fa2566,MV7FX6WG-1,9e177226-ca90-4db1-8339-2965d12c1576,P3954,4265319825574,,...,2021-11-20T00:00:00.000Z,,,,,,,,,
18,FEE,PURCHASE_FEE_FIXED,2021-11-12T06:06:26.373Z,2021-11-12T17:45:38.000Z,5bbed895-6b5b-5773-911a-9b74f58bc1b7,JWS70R97-1,5c1dcee3-16a2-4212-8a5e-5a4c6b1867c1,P3919,4263210287270,,...,2021-11-16T00:00:00.000Z,,,,,,,,,
19,SALE,PURCHASE,2021-11-12T06:06:26.373Z,2021-11-12T17:45:38.000Z,5bbed895-6b5b-5773-911a-9b74f58bc1b7,JWS70R97-1,5c1dcee3-16a2-4212-8a5e-5a4c6b1867c1,P3919,4263210287270,,...,2021-11-16T00:00:00.000Z,,,,,,,,,
20,FEE,PURCHASE_FEE_PERCENTAGE,2021-11-12T06:06:26.373Z,2021-11-12T17:45:38.000Z,5bbed895-6b5b-5773-911a-9b74f58bc1b7,JWS70R97-1,5c1dcee3-16a2-4212-8a5e-5a4c6b1867c1,P3919,4263210287270,,...,2021-11-16T00:00:00.000Z,,,,,,,,,
21,SALE,PURCHASE,2021-11-04T19:49:07.060Z,2021-11-05T16:20:29.000Z,0db0e2a5-0240-49c2-9554-832764faf2fe,DKP2QB0W-1,c2434e14-9aca-49c0-92ff-43646aa1aa30,P3821,4249624346790,,...,2021-11-09T00:00:00.000Z,,,,,,,,,
22,FEE,PURCHASE_FEE_PERCENTAGE,2021-11-04T19:49:07.060Z,2021-11-05T16:20:29.000Z,0db0e2a5-0240-49c2-9554-832764faf2fe,DKP2QB0W-1,c2434e14-9aca-49c0-92ff-43646aa1aa30,P3821,4249624346790,,...,2021-11-09T00:00:00.000Z,,,,,,,,,
23,FEE,PURCHASE_FEE_FIXED,2021-11-04T19:49:07.060Z,2021-11-05T16:20:29.000Z,0db0e2a5-0240-49c2-9554-832764faf2fe,DKP2QB0W-1,c2434e14-9aca-49c0-92ff-43646aa1aa30,P3821,4249624346790,,...,2021-11-09T00:00:00.000Z,,,,,,,,,
24,FEE,PURCHASE_FEE_PERCENTAGE,2021-11-03T14:32:21.099Z,2021-11-03T18:46:56.000Z,89ba3b24-b810-4c24-8396-ed6e15300f9b,STCM4QWW-1,cbb9fb05-c8ce-47f8-a84c-6252704f076f,P3803,4247362535590,,...,2021-11-07T00:00:00.000Z,,,,,,,,,
25,SALE,PURCHASE,2021-11-03T14:32:21.099Z,2021-11-03T18:46:56.000Z,89ba3b24-b810-4c24-8396-ed6e15300f9b,STCM4QWW-1,cbb9fb05-c8ce-47f8-a84c-6252704f076f,P3803,4247362535590,,...,2021-11-07T00:00:00.000Z,,,,,,,,,
26,FEE,PURCHASE_FEE_FIXED,2021-11-03T14:32:21.099Z,2021-11-03T18:46:56.000Z,89ba3b24-b810-4c24-8396-ed6e15300f9b,STCM4QWW-1,cbb9fb05-c8ce-47f8-a84c-6252704f076f,P3803,4247362535590,,...,2021-11-07T00:00:00.000Z,,,,,,,,,
27,SALE,PURCHASE,2021-10-31T19:08:03.900Z,2021-11-02T15:45:45.000Z,1abc659e-fd77-4e0d-98d7-c4a767ef2cf7,J46Q2X3S-1,f83ae4c7-5693-4e62-9a92-dfc06eaba27d,P3741,4242567430310,,...,2021-11-06T00:00:00.000Z,,,,,,,,,
28,FEE,PURCHASE_FEE_FIXED,2021-10-31T19:08:03.900Z,2021-11-02T15:45:45.000Z,1abc659e-fd77-4e0d-98d7-c4a767ef2cf7,J46Q2X3S-1,f83ae4c7-5693-4e62-9a92-dfc06eaba27d,P3741,4242567430310,,...,2021-11-06T00:00:00.000Z,,,,,,,,,
29,FEE,PURCHASE_FEE_PERCENTAGE,2021-10-31T19:08:03.900Z,2021-11-02T15:45:45.000Z,1abc659e-fd77-4e0d-98d7-c4a767ef2cf7,J46Q2X3S-1,f83ae4c7-5693-4e62-9a92-dfc06eaba27d,P3741,4242567430310,,...,2021-11-06T00:00:00.000Z,,,,,,,,,
30,FEE,PURCHASE_FEE_FIXED,2021-10-30T12:59:34.154Z,2021-11-02T14:48:05.000Z,c6be5798-d688-43ce-8e18-d8d43972a9a7,FB3QG5MC-1,85c10331-bf7c-4d08-a24f-ccadaf524195,P3713,4240166584486,,...,2021-11-06T00:00:00.000Z,,,,,,,,,
31,FEE,PURCHASE_FEE_PERCENTAGE,2021-10-30T12:59:34.154Z,2021-11-02T14:48:05.000Z,c6be5798-d688-43ce-8e18-d8d43972a9a7,FB3QG5MC-1,85c10331-bf7c-4d08-a24f-ccadaf524195,P3713,4240166584486,,...,2021-11-06T00:00:00.000Z,,,,,,,,,
32,SALE,PURCHASE,2021-10-30T12:59:34.154Z,2021-11-02T14:48:05.000Z,c6be5798-d688-43ce-8e18-d8d43972a9a7,FB3QG5MC-1,85c10331-bf7c-4d08-a24f-ccadaf524195,P3713,4240166584486,,...,2021-11-06T00:00:00.000Z,,,,,,,,,
33,SALE,PURCHASE,2021-10-29T22:07:11.323Z,2021-11-01T14:18:26.000Z,b2b479bc-9d4a-4143-830a-d8478f90b2f8,CHQRT6TD-1,c75d948a-4e42-4b6d-9ce5-a0b43fc3f390,P3703,4239137210534,,...,2021-11-05T00:00:00.000Z,,,,,,,,,
34,FEE,PURCHASE_FEE_PERCENTAGE,2021-10-29T22:07:11.323Z,2021-11-01T14:18:26.000Z,b2b479bc-9d4a-4143-830a-d8478f90b2f8,CHQRT6TD-1,c75d948a-4e42-4b6d-9ce5-a0b43fc3f390,P3703,4239137210534,,...,2021-11-05T00:00:00.000Z,,,,,,,,,
35,FEE,PURCHASE_FEE_FIXED,2021-10-29T22:07:11.323Z,2021-11-01T14:18:26.000Z,b2b479bc-9d4a-4143-830a-d8478f90b2f8,CHQRT6TD-1,c75d948a-4e42-4b6d-9ce5-a0b43fc3f390,P3703,4239137210534,,...,2021-11-05T00:00:00.000Z,,,,,,,,,

In [9]:
kl[["Date","Useless"]]=kl["capture_date"].str.split("T",n=1,expand=True)
kl[["payout","Useless_1"]]=kl["payout_date"].str.split("T",n=1,expand=True)

In [10]:
kl=kl[["Date","type","merchant_reference1","amount","payout"]]

In [11]:
kl.head()

         Date  type merchant_reference1  amount      payout
0  2021-11-28  SALE               P4204  124.80  2021-12-02
1  2021-11-28   FEE               P4204    0.30  2021-12-02
2  2021-11-28   FEE               P4204    2.48  2021-12-02
3  2021-11-28   FEE               P4195    0.92  2021-12-02
4  2021-11-28  SALE               P4195   46.35  2021-12-02

In [12]:
kl_sales=kl[kl["type"]!="RETURN"]
KL_return=kl[kl["type"]=="RETURN"]

In [13]:
kl_sales['amount'].dtype

dtype('O')

In [14]:
kl_sales["amount_net"]=np.where(kl_sales["type"]=="FEE",kl_sales["amount"].astype('float64')*(-1),kl_sales["amount"])

In [15]:
kl_sales_sum=kl_sales[["merchant_reference1","amount_net"]]

In [16]:
kl_sales_sum["amount_net"]=kl_sales_sum["amount_net"].astype('float64')

<ipython-input-16-fd40d555770e>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  kl_sales_sum["amount_net"]=kl_sales_sum["amount_net"].astype('float64')

In [17]:
kl_sales_sum=kl_sales_sum.groupby("merchant_reference1").sum()

In [18]:
kl_sales_sum

                     amount_net
merchant_reference1
P3703                    118.83
P3713                     67.62
P3741                    299.01
P3803                     61.69
P3821                    142.40
P3919                     67.55
P3954                    126.13
P4041                    182.34
P4075                     81.98
P4098                    144.21
P4195                     45.13
P4204                    122.02

In [19]:
KL_return["amount_net"]=KL_return["amount"].astype("float64")

In [20]:
KL_return["amount"]=KL_return["amount"].astype("float64")*(-1)
KL_return["amount_net"]=KL_return["amount_net"].astype("float64")*(-1)
KL_return=KL_return.drop("type",axis=1)

In [21]:
KL_return=KL_return[["Date","merchant_reference1","amount","amount_net","payout"]]
KL_return

Empty DataFrame
Columns: [Date, merchant_reference1, amount, amount_net, payout]
Index: []

In [22]:
kl_sales_join=kl[kl["type"]=="SALE"]

In [23]:
kl_sales_join

          Date  type merchant_reference1  amount      payout
0   2021-11-28  SALE               P4204  124.80  2021-12-02
4   2021-11-28  SALE               P4195   46.35  2021-12-02
6   2021-11-23  SALE               P4098  147.44  2021-11-27
11  2021-11-23  SALE               P4075   83.95  2021-11-27
13  2021-11-19  SALE               P4041  186.35  2021-11-23
17  2021-11-16  SALE               P3954  129.00  2021-11-20
19  2021-11-12  SALE               P3919   69.23  2021-11-16
21  2021-11-05  SALE               P3821  145.60  2021-11-09
25  2021-11-03  SALE               P3803   63.25  2021-11-07
27  2021-11-02  SALE               P3741  305.39  2021-11-06
32  2021-11-02  SALE               P3713   69.30  2021-11-06
33  2021-11-01  SALE               P3703  121.55  2021-11-05

In [24]:
kl_result=pd.merge(kl_sales_join,kl_sales_sum, how="left",on="merchant_reference1")

In [25]:
kl_result=kl_result[["Date","merchant_reference1","amount","amount_net","payout"]]

In [26]:
kl_result

          Date merchant_reference1  amount  amount_net      payout
0   2021-11-28               P4204  124.80      122.02  2021-12-02
1   2021-11-28               P4195   46.35       45.13  2021-12-02
2   2021-11-23               P4098  147.44      144.21  2021-11-27
3   2021-11-23               P4075   83.95       81.98  2021-11-27
4   2021-11-19               P4041  186.35      182.34  2021-11-23
5   2021-11-16               P3954  129.00      126.13  2021-11-20
6   2021-11-12               P3919   69.23       67.55  2021-11-16
7   2021-11-05               P3821  145.60      142.40  2021-11-09
8   2021-11-03               P3803   63.25       61.69  2021-11-07
9   2021-11-02               P3741  305.39      299.01  2021-11-06
10  2021-11-02               P3713   69.30       67.62  2021-11-06
11  2021-11-01               P3703  121.55      118.83  2021-11-05

In [27]:
result=pd.concat([kl_result,KL_return])

In [28]:
result

          Date merchant_reference1  amount  amount_net      payout
0   2021-11-28               P4204  124.80      122.02  2021-12-02
1   2021-11-28               P4195   46.35       45.13  2021-12-02
2   2021-11-23               P4098  147.44      144.21  2021-11-27
3   2021-11-23               P4075   83.95       81.98  2021-11-27
4   2021-11-19               P4041  186.35      182.34  2021-11-23
5   2021-11-16               P3954  129.00      126.13  2021-11-20
6   2021-11-12               P3919   69.23       67.55  2021-11-16
7   2021-11-05               P3821  145.60      142.40  2021-11-09
8   2021-11-03               P3803   63.25       61.69  2021-11-07
9   2021-11-02               P3741  305.39      299.01  2021-11-06
10  2021-11-02               P3713   69.30       67.62  2021-11-06
11  2021-11-01               P3703  121.55      118.83  2021-11-05

In [29]:
result.to_csv("C://Users//shawnhe//Desktop//kl_result.csv",index=False)